const Types = {
  VALIDATE_USER_REQ: "VALIDATE_USER_REQ",
  VALIDATE_USER_SUCCESS: "VALIDATE_USER_SUCCESS",
  VALIDATE_USER_FAIL: "VALIDATE_USER_FAIL",
  CLEAR_LOGIN_STORE: "CLEAR_LOGIN_STORE"
};

export default Types;
