const Types = {
  GET_PEOPLE_REQ: "GET_PEOPLE_REQ",
  GET_PEOPLE_SUCCESS: "GET_PEOPLE_SUCCESS",
  GET_PEOPLE_FAIL: "GET_PEOPLE_FAIL",
  UPDATE_ROW: "UPDATE_ROW",
  GET_HOMEWORLD_REQ: "GET_HOMEWORLD_REQ",
  GET_HOMEWORLD_SUCCESS: "GET_HOMEWORLD_SUCCESS",
  CLEAR_USERDETAIL_STORE: "CLEAR_USERDETAIL_STORE"
};
export default Types;
